### ISSUE TITLE
Issue-✨ 查询用户资料接口实现

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#10]
Automated Review Comments
Issues in controllers/user.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
Issues in services/user.go:
  - (3, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
Issues in stores/user.go:
  - (1, 'Line exceeds 80 characters')
Issues in utils/serializers/user.go:
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')

**Comment by johnsmith0212** [comment]
I got it.
