### ISSUE TITLE
Issue-✨ 分离博客和图片上传接口 优化部分代码实现

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#106]
Automated Review Comments
Issues in controllers/comment.go:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in controllers/post.go:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
Issues in main.go:
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
Issues in models/user.go:
  - (3, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
Issues in rontines/avatar.go:
  - (2, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
Issues in rontines/cache_img.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
Issues in services/post.go:
  - (5, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
Issues in stores/post.go:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
Issues in stores/user.go:
  - (9, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
Issues in types/request.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in utils/serializers/post.go:
  - (1, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
