### ISSUE TITLE
Issue-✨ 设置Github Action Linter

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#14]
Automated Review Comments
Issues in .github/workflows/golangci-lint.yml:
  - (12, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')

**Comment by martinjbrown776** [comment]
I got it.
