### ISSUE TITLE
Issue-✨ 添加压缩中间件

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#24]
Automated Review Comments
Issues in config/config.go:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in configuration.toml:
  - (3, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in main.go:
  - (2, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
