### ISSUE TITLE
Issue-✨ 实现用户登录接口

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#28]
Automated Review Comments
Issues in controllers/user.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
Issues in go.sum:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in models/user.go:
  - (29, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
Issues in services/user.go:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in stores/user.go:
  - (9, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
Issues in types/auth_body.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in types/bearer_token.go:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in utils/encryptor/password.go:
  - (12, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
Issues in utils/generator/token.go:
  - (10, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
Issues in utils/parser/token.go:
  - (20, 'Line exceeds 80 characters')
Issues in utils/serializers/user.go:
  - (1, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
