### ISSUE TITLE
Issue-✨ 添加BearerToken验证中间件
🎨 提取状态码常数 减少硬编码

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#34]
Automated Review Comments
Issues in controllers/user.go:
  - (9, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (105, 'TODO found')
Issues in main.go:
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
Issues in middleware/auth.go:
  - (37, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
Issues in stores/user.go:
  - (5, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
Issues in utils/parser/token.go:
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in utils/serializers/response.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
Issues in utils/valider/token.go:
  - (5, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
