### ISSUE TITLE
Issue-✨ 初步实现头像上传接口

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#35]
Automated Review Comments
Issues in controllers/user.go:
  - (1, 'Line exceeds 80 characters')
  - (5, 'TODO found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
Issues in go.sum:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
Issues in services/user.go:
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
Issues in stores/user.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
Issues in utils/converter/avatar.go:
  - (5, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
Issues in utils/valider/avatar.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (57, 'Hardcoded string found')

**Comment by christianagalindo7** [comment]
I got it.
