### ISSUE TITLE
Issue-✨ 增加限制单用户Token数量上限
🔧 修复部分webp图像无法正常解码
🎨 优化读取图片信息的代码格式

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#45]
Automated Review Comments
Issues in middleware/auth.go:
  - (1, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
Issues in models/user.go:
  - (2, 'Line exceeds 80 characters')
Issues in services/user.go:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in stores/user.go:
  - (1, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
Issues in utils/converter/avatar.go:
  - (11, 'Line exceeds 80 characters')
Issues in utils/generator/token.go:
  - (6, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
Issues in utils/valider/avatar.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')

**Comment by johnsmith0212** [comment]
I got it.
