### ISSUE TITLE
Issue-✨ 新增修改密码和修改用户信息接口

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#49]
Automated Review Comments
Issues in controllers/user.go:
  - (1, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
Issues in main.go:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in middleware/auth.go:
  - (1, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in models/user.go:
  - (2, 'Line exceeds 80 characters')
Issues in services/user.go:
  - (9, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
Issues in stores/user.go:
  - (1, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
Issues in types/User.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in utils/converter/avatar.go:
  - (11, 'Line exceeds 80 characters')
Issues in utils/generator/token.go:
  - (5, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
Issues in utils/valider/avatar.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
