### ISSUE TITLE
Issue-✨ 用户注册接口实现

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#6]
Automated Review Comments
Issues in config/config.go:
  - (5, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in configuration.toml:
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in controllers/user.go:
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
Issues in go.sum:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
Issues in loggers/loggers.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
Issues in main.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
Issues in models/user.go:
  - (10, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
Issues in serializers/response.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
Issues in services/user.go:
  - (5, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
Issues in stores/user.go:
  - (32, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
Issues in utils/valider/password.go:
  - (9, 'Hardcoded string found')
Issues in utils/valider/username.go:
  - (9, 'Hardcoded string found')

**Comment by johnsmith0212** [comment]
I got it.
