### ISSUE TITLE
Issue-✨ 新增博文和评论数据库模型

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#62]
Automated Review Comments
Issues in go.sum:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in models/post.go:
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
