### ISSUE TITLE
Issue-✨ 指定服务器监听地址 防止调试每次启动时弹防火墙提示

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#66]
Automated Review Comments
Issues in configs/config.go:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in configuration.toml:
  - (3, 'Hardcoded string found')
Issues in main.go:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
