### ISSUE TITLE
Issue-✨ 新增博文和评论框架和博文列表，创建评论的接口

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#70]
Automated Review Comments
Issues in configs/config.go:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in configuration.toml:
  - (3, 'Hardcoded string found')
Issues in controllers/comment.go:
  - (44, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
Issues in controllers/post.go:
  - (39, 'Hardcoded string found')
Issues in main.go:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
Issues in services/comment.go:
  - (31, 'Line exceeds 80 characters')
Issues in stores/comment.go:
  - (26, 'Line exceeds 80 characters')
Issues in types/request.go:
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
