### ISSUE TITLE
Issue-✨ 新增博文和评论框架和博文列表，创建评论的接口 的修改

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#72]
Automated Review Comments
Issues in controllers/comment.go:
  - (4, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
Issues in controllers/post.go:
  - (7, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
Issues in main.go:
  - (5, 'Hardcoded string found')
Issues in types/request.go:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
