### ISSUE TITLE
Issue-🔧 修复默认头像不显示

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#74]
Automated Review Comments
Issues in configs/config.go:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in configuration.toml:
  - (3, 'Hardcoded string found')
Issues in main.go:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
Issues in types/request.go:
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')

**Comment by christianagalindo7** [comment]
I got it.
