### ISSUE TITLE
Issue-🎨 优化代码结构注释

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#8]
Automated Review Comments
Issues in controllers/user.go:
  - (11, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
Issues in stores/user.go:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
Issues in utils/serializers/response.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
