### ISSUE TITLE
Issue-🔧 修改逻辑层面的业务代码

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#80]
Automated Review Comments
Issues in configs/config.go:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in configuration.toml:
  - (3, 'Hardcoded string found')
Issues in controllers/comment.go:
  - (9, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
Issues in main.go:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
Issues in services/comment.go:
  - (20, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
Issues in types/request.go:
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')

**Comment by martinjbrown776** [comment]
I got it.
