### ISSUE TITLE
Issue-✨新增Post和Comment相关接口基本实现

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#82]
Automated Review Comments
Issues in config/config.go:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in controllers/comment.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (209, 'Line exceeds 80 characters')
  - (209, 'Hardcoded string found')
Issues in controllers/post.go:
  - (1, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (178, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (183, 'Line exceeds 80 characters')
  - (186, 'Hardcoded string found')
Issues in controllers/user.go:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
Issues in main.go:
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
Issues in services/comment.go:
  - (5, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (79, 'TODO found')
  - (85, 'Hardcoded string found')
  - (106, 'TODO found')
  - (112, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
Issues in services/post.go:
  - (45, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
Issues in services/user.go:
  - (1, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in stores/comment.go:
  - (5, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
Issues in stores/post.go:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
Issues in types/request.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
Issues in utils/converters/avatar.go:
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
Issues in utils/converters/post.go:
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (103, 'Hardcoded string found')
Issues in utils/serializers/comment.go:
  - (9, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (28, 'TODO found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (44, 'TODO found')
  - (59, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
Issues in utils/serializers/post.go:
  - (9, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
Issues in utils/validers/image.go:
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (67, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
