### ISSUE TITLE
Issue-Merge branch 'dev' into dev

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#84]
Automated Review Comments
Issues in configs/config.go:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in configuration.toml:
  - (3, 'Hardcoded string found')
Issues in main.go:
  - (6, 'Line exceeds 80 characters')

**Comment by williamddobson3** [comment]
I got it.
